# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfinal', '0002_remove_usuario_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='Libro',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Libro',
            field=models.ManyToManyField(related_name='libros', to='exfinal.Libros'),
        ),
    ]
